name: Python 3.9.21
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9.21
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.21
    - name: Install dependencies
      run: |
        make install
    - name: Lint with Pylint
      run: |
        make lint
    - name: Format code with Python black
      run: |
        make format
